### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by t826** [fengkx/svelte-aplayer#1]
错误信息：
Line must be greater than or equal to 1, got -1

**Comment by fengkx** [comment]
请提供详细信息和复现

**Comment by t826** [comment]
```shell
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:21664:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:21733:22)
    at C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73351:34
    at String.replace (<anonymous>)
    at C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73341:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73340:10)
    at Object.ssrFixStacktrace (C:\Users\Lenovo\Desktop\svelte\my-app\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73679:36)
    at Object.handle_error (file:///C:/Users/Lenovo/Desktop/svelte/my-app/node_modules/@sveltejs/kit/dist/chunks/index.js:3480:13)
    at respond$1 (file:///C:/Users/Lenovo/Desktop/svelte/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1112:12)
```

**Comment by t826** [comment]
![image](https://user-images.githubusercontent.com/67208386/127726329-2ed8d047-0584-4570-a127-a45f91743bc4.png)

**Comment by fengkx** [comment]
贴代码不要截图，谢谢

**Comment by t826** [comment]
```javascript
<script>
	import 'svelte-aplayer/dist/svelte/style.css';
	import Aplayer from 'svelte-aplayer/dist/svelte/svelte-aplayer.es.js';
	let list = [
		{
			name: '君の知らない物語',
			artist: 'supercell',
			cover: 'https://blog-static.fengkx.top/svelte-aplayer/bakemonogatari-ed.jpg',
			url: 'https://blog-static.fengkx.top/svelte-aplayer/bakemonogatari-ed.mp3'
		},
		{
			name: '晴天',
			artist: '周杰伦',
			url:
				'http://59.110.45.28/m/api/url/yqb/id/b40dcNS6Lz3mysj0ZKzJi6B0VWjanioXjt7njiXWuEanRNY/format/320kmp3',
			cover:
				'http://59.110.45.28/m/api/cover/yqb/id/b40dcNS6Lz3mysj0ZKzJi6B0VWjanioXjt7njiXWuEanRNY'
		}
	];
</script>

 <Aplayer audio={list} /> 

```

**Comment by t826** [comment]
怎么开启吸底模式呢？

**Comment by fengkx** [comment]
无法复现， 吸地模式没实现。你可以clone repo 自己debug
